'use client';
import { useLanguage } from '@/i18n/LanguageContext';
import { COUNTRY_CODES, type ContactDetails } from '@/lib/contact';
import { getStates } from '@/lib/formation';
import { addressWarning, type BusinessAddress, isPoBox } from '@/lib/business-mail';

export default function BusinessMailStep({ state, choice, onChoice, different, onDifferent, address, onAddress, contact }: { state: string; choice: 'own' | 'virtual'; onChoice: (value: 'own' | 'virtual') => void; different: boolean; onDifferent: (value: boolean) => void; address: BusinessAddress; onAddress: (value: BusinessAddress) => void; contact: ContactDetails }) {
  const { lang } = useLanguage();
  const es = lang === 'es';
  const names = new Intl.DisplayNames([lang], { type: 'region' });
  const field = (key: keyof BusinessAddress, label: string, autoComplete: string, required = true) => <div className="form-group"><label htmlFor={`business-${key}`}>{label}</label><input id={`business-${key}`} autoComplete={`section-business ${autoComplete}`} required={required} maxLength={key === 'postalCode' ? 20 : key === 'city' || key === 'region' ? 100 : 200} pattern={key === 'postalCode' && address.country === 'US' ? '[0-9]{5}(-[0-9]{4})?' : required ? '.*\\S.*' : undefined} value={address[key]} onChange={e => { e.target.setCustomValidity((key === 'street' || key === 'addressLine2') && isPoBox(e.target.value) ? (es ? 'Ingresá una dirección física, no un P.O. Box.' : 'Enter a physical street address, not a P.O. Box.') : ''); onAddress({ ...address, [key]: e.target.value }); }} /></div>;
  return <div className="business-mail" lang={es ? 'es' : 'en'}>
    <p className="contact-intro">{es ? '¿Cómo querés recibir el correo de tu empresa? La dirección elegida se utilizará para preparar tus documentos de constitución.' : 'How would you like to receive mail for your business? Your chosen address will be used to prepare your formation documents.'}</p>
    <section className="mail-offer">
      <div className="mail-offer-heading"><h2>{es ? 'Dirección virtual + buzón' : 'Virtual Address + Mailbox'}</h2><span>{es ? 'Primer mes gratis' : 'First month free'}</span></div>
      <div className="mail-showcase">
        <ul>{(es ? ['Separá tu dirección personal de la de tu negocio','Recibí correspondencia en una dirección física','Consultá tu correo digitalizado desde cualquier lugar','Recibí avisos cuando llegue nueva correspondencia'] : ['Keep your personal and business addresses separate','Receive business mail at a physical address','Access your scanned mail from anywhere','Get notified when new mail arrives']).map(item => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul>
        <div className="mail-phones" role="img" aria-label={es ? 'Mockups de celulares con un buzón digital de Just My LLC' : 'Phone mockups showing a Just My LLC digital mailbox'}>
          <div className="mail-phone phone-inbox" aria-hidden="true"><div className="phone-island"/><div className="phone-status">9:41 <span>▮▮▮ ▰</span></div><b className="phone-brand">just my llc<span>®</span></b><p className="phone-greeting">YOUR BUSINESS, CONNECTED</p><h3>My mailbox</h3><div className="phone-address"><small>VIRTUAL ADDRESS</small><strong>{state}</strong><span>Business mail, all in one place.</span></div><h4>Recent mail <span>03</span></h4>{['State correspondence','Business document','New letter'].map((label,i)=><div className="phone-letter" key={label}><span>▤</span><div><b>{label}</b><small>{i === 0 ? 'Ready to view' : 'Scanned document'}</small></div><i>›</i></div>)}<div className="phone-nav">⌂ <b>▤</b> ⚙</div></div>
          <div className="mail-phone phone-confirm" aria-hidden="true"><div className="phone-island"/><div className="phone-status">9:41 <span>▮▮▮ ▰</span></div><b className="phone-brand">just my llc<span>®</span></b><div className="phone-check">✓</div><h3>Your mail.<br/>Within reach.</h3><p>A home for your business mail, wherever you are.</p><div className="phone-preview-card"><small>YOUR MAILBOX</small><strong>{state}</strong><span>Organized. Connected. Simple.</span></div><div className="phone-demo">{es ? 'Vista ilustrativa' : 'Illustrative preview'}</div></div>
        </div>
      </div>
      <fieldset className="mail-choices"><legend className="sr-only">{es ? 'Elegí cómo recibir correo' : 'Choose how to receive mail'}</legend>{(['virtual','own'] as const).map(value => <label key={value} className={choice === value ? 'selected' : ''}><input type="radio" name="mail-choice" value={value} checked={choice === value} onChange={() => onChoice(value)} /><span>{value === 'virtual' ? (es ? 'Usar dirección virtual + buzón' : 'Use Virtual Address + Mailbox') : (es ? 'Usaré mi propia dirección' : 'I’ll use my own address')}</span></label>)}</fieldset>
      <p className="mail-terms">{es ? 'Primer mes gratis, luego $29/mes. Cancelá cuando quieras.' : 'First month free, then $29/month. Cancel anytime.'}<small>{es ? 'Sujeto a disponibilidad y confirmación antes de activar el servicio. Seleccionarlo no inicia una suscripción. Cancelar podría requerir actualizar la dirección ante el estado.' : 'Subject to availability and confirmation before activation. Selecting this does not start a subscription. Cancellation may require updating your address with the state.'}</small></p>
      {choice === 'own' && <div className="mail-own-address"><label className="mail-different"><input type="checkbox" checked={different} onChange={e => onDifferent(e.target.checked)} /><span>⌖</span>{es ? 'Usar una dirección diferente' : 'Use a different address'}</label>
        {!different ? <div className="mail-contact-address"><strong>{es ? 'Usar mi dirección de contacto' : 'Use my contact address'}</strong><p>{[contact.street,contact.addressLine2,contact.city,contact.region,contact.postalCode,contact.country].filter(Boolean).join(', ')}</p></div> : <>
        <div className="form-group"><label htmlFor="business-country">{es ? 'País' : 'Country'}</label><select id="business-country" autoComplete="section-business country" value={address.country} onChange={e=>onAddress({...address,country:e.target.value,region:'',postalCode:''})}>{COUNTRY_CODES.map(code=>({code,name:names.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name,lang)).map(({code,name})=><option key={code} value={code}>{name}</option>)}</select></div>
        <div className="contact-street">{field('street',es ? 'Dirección' : 'Street address','address-line1')}{field('addressLine2',es ? 'Departamento, piso, etc. (opcional)' : 'Address (cont.) — optional','address-line2',false)}</div>
        <div className="contact-city">{field('city',es ? 'Ciudad' : 'City','address-level2')}{address.country === 'US' ? <div className="form-group"><label htmlFor="business-region">{es ? 'Estado' : 'State'}</label><select id="business-region" autoComplete="section-business address-level1" required value={address.region} onChange={e=>onAddress({...address,region:e.target.value})}><option value="">{es ? 'Elegí un estado' : 'Select state'}</option>{getStates('LLC').map(item=><option key={item}>{item}</option>)}</select></div> : field('region',es ? 'Estado / provincia' : 'State / province','address-level1',false)}{field('postalCode',es ? 'Código postal' : 'ZIP / postal code','postal-code',address.country === 'US')}</div>
        </>}
      </div>}
    </section>
    {choice === 'own' ? <aside className="mail-warning"><span aria-hidden="true">⚠</span><div><strong>{es ? 'Tené en cuenta al usar tu propia dirección:' : 'Keep in mind when using your own address:'}</strong><ul><li>{es ? 'Puede aparecer en documentos públicos presentados ante el estado.' : 'It may appear in public documents filed with the state.'}</li><li>{es ? 'Tu correspondencia se entregará allí; no se digitalizará por este servicio.' : 'Your business mail will be delivered there, not scanned by this service.'}</li><li>{addressWarning(state,es)}</li></ul></div></aside> : <p className="formation-note" role="status">{es ? `Guardaremos tu solicitud de dirección virtual en ${state}. Confirmaremos disponibilidad antes de presentar tu documentación.` : `We’ll save your request for a virtual address in ${state}. Availability will be confirmed before filing your documents.`}</p>}
  </div>;
}
