'use client';
import { useState } from 'react';
import { useLanguage } from '@/i18n/LanguageContext';
import { DOMAIN_PRICE_USD, type DomainRegistration } from '@/lib/domains';
import type { ContactDetails } from '@/lib/contact';
export default function DomainStep({companyName,value,onChange,contact,onContactChange}:{companyName:string;value:DomainRegistration|null;onChange:(value:DomainRegistration|null)=>void;contact:ContactDetails;onContactChange:(contact:ContactDetails)=>void}) {
  const {lang}=useLanguage(); const es=lang==='es';
  const suggested=companyName.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,63);
  const [domain,setDomain]=useState(value?.name || `${suggested || 'mybusiness'}.com`);
  const [status,setStatus]=useState<'idle'|'loading'|'free'|'taken'|'premium'|'error'>(value?'free':'idle');
  async function search() {
    onChange(null);setStatus('loading');
    try {const response=await fetch('/api/domains/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain})});const data=await response.json();if(!response.ok) throw new Error();setDomain(data.name);setStatus(!data.available?'taken':data.premium?'premium':'free');}catch{setStatus('error');}
  }
  const field=(key:'street'|'number'|'phoneCountry'|'phoneArea'|'phoneNumber',label:string,placeholder:string,pattern?:string)=><div className="form-group"><label htmlFor={`domain-${key}`}>{label}</label><input id={`domain-${key}`} required pattern={pattern||'.*\\S.*'} placeholder={placeholder} value={value?.[key]||''} maxLength={key==='street'?200:key==='number'?20:key==='phoneCountry'?4:key==='phoneArea'?8:15} onChange={e=>value&&onChange({...value,[key]:e.target.value})}/></div>;
  return <section><h2 className="t-h4">{es?'Dale a tu empresa su propio dominio':'Give your business its own domain'}</h2><p className="contact-intro">{es?'Empezá con un dominio inspirado en el nombre de tu empresa.':'Start with a domain inspired by your company name.'}</p><div className="ein-included"><span aria-hidden="true">!</span><div><strong>{es?'Asegurá el nombre antes de presentar tu LLC':'Secure your name before filing your LLC'}</strong><p>{es?'El nombre de tu LLC puede aparecer en registros públicos. Constituirla no reserva su dominio: otra persona podría registrarlo mientras siga disponible.':'Your LLC name may appear in public records. Forming it does not reserve its domain: someone else could register it while it remains available.'}</p></div></div><div className="form-group"><label htmlFor="domain-search">{es?'Buscá tu dominio .com':'Find your .com domain'}</label><input id="domain-search" value={domain} disabled={status==='loading'} onChange={e=>{setDomain(e.target.value);setStatus('idle');onChange(null);}} autoCapitalize="none" spellCheck={false}/></div><button type="button" className="btn btn-accent" disabled={status==='loading'} onClick={search}>{status==='loading'?(es?'Buscando…':'Searching…'):(es?'Buscar disponibilidad':'Check availability')}</button><p className="t-h4" style={{marginTop:24}}>.com · ${DOMAIN_PRICE_USD} / {es?'año':'year'}</p><p role="status">{status==='free'?(es?'Disponible ahora.':'Available now.'):status==='taken'?(es?'Este dominio ya está registrado. Probá otro nombre.':'This domain is already registered. Try another name.'):status==='premium'?(es?'Este es un dominio premium y no está incluido en la tarifa de $16. Probá otro nombre.':'This is a premium domain, outside the $16 offer. Try another name.'):status==='error'?(es?'No pudimos consultar la disponibilidad. Usá un nombre .com o continuá sin dominio.':'We couldn’t check availability. Use a .com name or continue without a domain.') : ''}</p>
    {status==='free' && <label className="saved-contact-choice" style={{marginTop:24}}><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked?{name:domain,street:contact.street,number:'',phoneCountry:'',phoneArea:'',phoneNumber:'',consent:true}:null)}/><span>{es?'Agregar':'Add'} {domain} · $16<small>{es?'Un año de registro. Sin renovación automática.':'One year of registration. No automatic renewal.'}</small></span></label>}
    {value && <div style={{marginTop:28}}><h3 className="t-h4">{es?'Titular del dominio':'Domain registrant'}: {contact.firstName} {contact.lastName}</h3><p className="formation-note">{es?'Usaremos tu nombre, correo y dirección de contacto para registrarlo a tu nombre. Confirmá la calle, el número y el teléfono internacional.':'We’ll use your contact name, email and address to register it in your name. Confirm your street, building number and international phone number.'}</p><div className="form-row">{field('street',es?'Calle (sin número)':'Street (without number)','')}{field('number',es?'Número':'Building number','')}</div><div className="form-group"><label htmlFor="domain-postcode">{es?'Código postal':'Postal code'}</label><input id="domain-postcode" required pattern=".*\S.*" maxLength={20} value={contact.postalCode} onChange={e=>onContactChange({...contact,postalCode:e.target.value})}/></div><div className="form-row">{field('phoneCountry',es?'Código de país':'Country calling code','+1','\\+[1-9][0-9]{0,2}')}{field('phoneArea',es?'Código de área':'Area code','305','[0-9]{1,8}')}{field('phoneNumber',es?'Número local':'Local phone number','5550123','[0-9]{3,15}')}</div><p className="formation-note">{es?'Al continuar, autorizás el registro por un año mediante Openprovider y el envío de estos datos al registrador. La disponibilidad se confirma al registrar después del pago. Si falla, revisaremos el pedido y te contactaremos.':'By continuing, you authorize one year of registration through Openprovider and sharing these details with the registrar. Availability is confirmed during registration after payment. If it fails, we’ll review your order and contact you.'}</p></div>}
    {!value && <p className="formation-note">{es?'Podés continuar sin agregar un dominio. La búsqueda no lo reserva.':'You can continue without a domain. Searching does not reserve it.'}</p>}
  </section>;
}
