'use client';
import { useLanguage } from '@/i18n/LanguageContext';
import { COUNTRY_CODES, type ContactDetails } from '@/lib/contact';
import type { BusinessMail } from '@/lib/business-mail';
import { emptyMember, type Member } from '@/lib/members';
export default function MembersStep({ members, onChange, contact, businessMail, entity }: { members: Member[]; onChange: (members: Member[]) => void; contact: ContactDetails; businessMail: BusinessMail | null; entity: string }) {
  const { lang } = useLanguage(); const es = lang === 'es';
  const countryNames = new Intl.DisplayNames([lang],{type:'region'});
  const hasName = !!(contact.firstName.trim() && contact.lastName.trim());
  function update(index: number, changes: Partial<Member>) { onChange(members.map((member,i)=>i === index ? {...member,...changes} : member)); }
  return <div className="members-step" lang={es ? 'es' : 'en'}>
    <p className="contact-intro">{es ? 'Indicá quiénes serán los propietarios de tu empresa. Podés reutilizar el nombre que ingresaste en tus datos de contacto.' : 'Tell us who will own your company. You can reuse the name entered in your contact information.'}</p>
    <div className="form-group"><label htmlFor="member-count">{entity === 'LLC' ? (es ? 'Cantidad de miembros / propietarios' : 'Number of members / owners') : (es ? 'Cantidad de accionistas' : 'Number of shareholders')}</label><select id="member-count" value={members.length} onChange={e=>{const count=Number(e.target.value);onChange(Array.from({length:count},(_,i)=>members[i] || emptyMember()));}}>{Array.from({length:100},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></div>
    {members.map((member,index)=><section className="member-card" key={index} aria-labelledby={`member-heading-${index}`}>
      <h2 className="t-h4" id={`member-heading-${index}`}>{entity === 'LLC' ? (es ? 'Miembro' : 'Member') : (es ? 'Accionista' : 'Shareholder')} {index+1}</h2>
      <fieldset className="mail-choices member-type"><legend className="sr-only">{es ? 'Tipo de propietario' : 'Owner type'} {index+1}</legend>{(['individual',...(entity === 'LLC' ? ['company'] : [])] as Member['type'][]).map(type=><label className={member.type === type ? 'selected' : ''} key={type}><input type="radio" name={`member-type-${index}`} checked={member.type === type} onChange={()=>update(index,{type,useContactName:false})}/><span>{type === 'individual' ? (es ? 'Persona' : 'Individual') : (es ? 'Empresa' : 'Company')}<small>{type === 'individual' ? (es ? 'El propietario es una persona.' : 'The owner is a person.') : (es ? 'El propietario es una empresa.' : 'The owner is a company.')}</small></span></label>)}</fieldset>
      {member.type === 'individual' && hasName && <div className="saved-contact member-saved-name"><label className="saved-contact-choice"><input type="checkbox" checked={member.useContactName} onChange={e=>update(index,{useContactName:e.target.checked,...(e.target.checked ? {firstName:contact.firstName,lastName:contact.lastName} : {firstName:'',lastName:''})})}/><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg><span>{contact.firstName} {contact.lastName}<small>{es ? 'Usar el nombre de contacto' : 'Use contact name'}</small></span></label></div>}
      <label className="mail-different"><input type="checkbox" checked={member.useBusinessAddress} onChange={e=>update(index,{useBusinessAddress:e.target.checked})}/><span aria-hidden="true">⌖</span>{businessMail?.choice === 'virtual' ? (es ? 'Usar la dirección virtual solicitada a Just My LLC' : 'Use the virtual address requested from Just My LLC') : (es ? 'Usar la dirección comercial de la empresa' : 'Use the company’s business address')}</label>
      {member.type === 'individual' ? <div className="form-row">{(['firstName','lastName'] as const).map((key,i)=><div className="form-group" key={key}><label htmlFor={`member-${index}-${key}`}>{es ? ['Nombre','Apellido'][i] : ['First name','Last name'][i]}</label><input id={`member-${index}-${key}`} required pattern=".*\S.*" maxLength={90} autoComplete={`section-member${index} ${i ? 'family-name' : 'given-name'}`} value={member.useContactName ? contact[key] : member[key]} onChange={e=>update(index,{[key]:e.target.value,useContactName:false,...(member.useContactName ? {[i ? 'firstName' : 'lastName']:contact[i ? 'firstName' : 'lastName']} : {})})}/></div>)}</div> : <div className="form-group"><label htmlFor={`member-${index}-company`}>{es ? 'Nombre legal de la empresa' : 'Legal company name'}</label><input id={`member-${index}-company`} required pattern=".*\S.*" maxLength={200} value={member.companyName} onChange={e=>update(index,{companyName:e.target.value})}/></div>}
      {!member.useBusinessAddress && <div className="member-address"><div className="form-group"><label htmlFor={`member-${index}-country`}>{es ? 'País' : 'Country'}</label><select id={`member-${index}-country`} value={member.address.country} onChange={e=>update(index,{address:{...member.address,country:e.target.value}})}>{COUNTRY_CODES.map(code=>({code,name:countryNames.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name,lang)).map(({code,name})=><option value={code} key={code}>{name}</option>)}</select></div><div className="member-address-grid">{(['street','addressLine2','city','region','postalCode'] as const).map((key,i)=><div className="form-group" key={key}><label htmlFor={`member-${index}-${key}`}>{es ? ['Dirección','Departamento, piso, etc. (opcional)','Ciudad','Estado / provincia (si corresponde)','Código postal (si corresponde)'][i] : ['Street address','Address (cont.) — optional','City','State / province (if applicable)','Postal code (if applicable)'][i]}</label><input id={`member-${index}-${key}`} required={i === 0 || i === 2} pattern={i === 0 || i === 2 ? '.*\\S.*' : undefined} maxLength={i < 2 ? 200 : i === 4 ? 20 : 100} value={member.address[key]} onChange={e=>update(index,{address:{...member.address,[key]:e.target.value}})}/></div>)}</div></div>}
      {member.useBusinessAddress && <aside className="member-address-notice"><strong>{businessMail?.choice === 'virtual' ? (es ? 'Elegiste usar una dirección virtual de Just My LLC.' : 'You chose a Just My LLC virtual address.') : (es ? 'Usaremos la dirección comercial para este propietario.' : 'We’ll use the business address for this owner.')}</strong><p>{businessMail?.choice === 'virtual' ? (es ? 'La dirección está pendiente de asignación. Confirmaremos su disponibilidad y si puede utilizarse para los datos del propietario antes de presentar el trámite.' : 'The address is awaiting assignment. We’ll confirm availability and whether it can be used for owner information before filing.') : businessMail?.address && Object.values(businessMail.address).filter(Boolean).join(', ')}</p></aside>}
    </section>)}
  </div>;
}
