'use client';
import { useLanguage } from '@/i18n/LanguageContext';
import type { ContactDetails } from '@/lib/contact';
import type { AgentForm } from '@/lib/registered-agent';
export default function RegisteredAgentStep({value,onChange,contact,state}:{value:AgentForm;onChange:(value:AgentForm)=>void;contact:ContactDetails;state:string}) {
  const {lang}=useLanguage(); const es=lang==='es';
  const update=(patch:Partial<AgentForm>)=>onChange({...value,...patch});
  const field=(key:'firstName'|'lastName'|'companyName'|'street'|'addressLine2'|'city'|'postalCode',label:string,max:number,required=true)=><div className="form-group"><label htmlFor={`agent-${key}`}>{label}</label><input id={`agent-${key}`} required={required} maxLength={max} pattern={key==='postalCode' ? '[0-9]{5}(-[0-9]{4})?' : required ? '.*\\S.*' : undefined} value={value.useContactName && (key==='firstName'||key==='lastName') ? contact[key] : value[key]} onChange={e=>update({[key]:e.target.value,...(key==='firstName'||key==='lastName' ? {useContactName:false,...(value.useContactName ? {firstName:contact.firstName,lastName:contact.lastName,[key]:e.target.value} : {})} : {})})}/></div>;
  const benefits=es ? ['Recepción de documentos legales y notificaciones oficiales','Una dirección para el agente distinta de tu domicilio personal','Avisos cuando se recibe documentación para tu empresa'] : ['Receive legal documents and official notices','Use an agent address separate from your home address','Get notified when documents arrive for your business'];
  const faqs=es ? [['Primer año incluido','El primer año del servicio está incluido. La renovación cuesta actualmente $149/año; confirmaremos sus condiciones antes de activarla.'],['Documentos organizados','Centralizá la recepción de notificaciones oficiales a través del servicio de agente registrado.'],['Dirección del agente','Confirmaremos el agente y su dirección en el estado de constitución antes de presentar los documentos. Este servicio no reemplaza un buzón comercial.'],['Disponibilidad en horario comercial','El agente designado debe estar disponible para recibir documentación durante el horario comercial.']] : [['Your first year is included','The first year of service is included. Renewal is currently $149/year; we’ll confirm the terms before activation.'],['Keep documents organized','Centralize receipt of official notices through your registered agent service.'],['Your registered agent address','We’ll confirm the agent and address in your formation state before filing. This service does not replace a business mailbox.'],['Available during business hours','The designated agent must be available to receive documents during business hours.']];
  return <div lang={es?'es':'en'}><p className="contact-intro">{es ? `Elegí quién recibirá los documentos legales y las notificaciones oficiales de tu empresa en ${state}.` : `Choose who will receive legal documents and official notices for your business in ${state}.`}</p><ul className="agent-benefits">{benefits.map(text=><li key={text}><span aria-hidden="true">✓</span>{text}</li>)}</ul>
    <fieldset className="mail-choices agent-options"><legend className="sr-only">{es?'Elegí tu agente registrado':'Choose your registered agent'}</legend>{(['service','own'] as const).map(choice=><label key={choice} className={value.choice===choice?'selected':''}><input type="radio" name="registered-agent" checked={value.choice===choice} onChange={()=>update({choice})}/><span>{choice==='service' ? (es?'Usar Just My LLC como agente registrado (primer año incluido)':'Use Just My LLC as my registered agent (first year included)') : (es?'Designaré mi propio agente registrado':'I’ll designate my own registered agent')}</span></label>)}</fieldset>
    {value.choice==='service' ? <div className="setup-help agent-help">{faqs.map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}</div> : <section className="member-card"><h2 className="t-h4">{es?'Información del agente':'Agent information'}</h2><p className="contact-intro">{es?`Ingresá una dirección física en ${state}, no un P.O. Box. El agente debe poder recibir documentos en horario comercial. Confirmaremos los requisitos aplicables antes de presentar el trámite.`:`Enter a physical street address in ${state}, not a P.O. Box. The agent must be available to receive documents during business hours. We’ll confirm applicable requirements before filing.`}</p>
      <fieldset className="mail-choices member-type"><legend className="sr-only">{es?'Tipo de agente':'Agent type'}</legend>{(['individual','company'] as const).map(type=><label key={type} className={value.type===type?'selected':''}><input type="radio" name="agent-type" checked={value.type===type} onChange={()=>update({type,useContactName:false})}/><span>{type==='individual'?(es?'Persona':'Individual'):(es?'Empresa':'Company')}<small>{type==='individual'?(es?'El agente será una persona.':'The agent will be an individual.'):(es?'El agente será otra empresa.':'The agent will be another company.')}</small></span></label>)}</fieldset>
      {value.type==='individual' && contact.firstName.trim() && contact.lastName.trim() && <div className="saved-contact"><label className="saved-contact-choice"><input type="checkbox" checked={value.useContactName} onChange={e=>update({useContactName:e.target.checked,firstName:e.target.checked?contact.firstName:'',lastName:e.target.checked?contact.lastName:''})}/><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg><span>{contact.firstName} {contact.lastName}<small>{es?'Usar el nombre de contacto':'Use contact name'}</small></span></label></div>}
      {value.type==='individual'?<div className="form-row">{field('firstName',es?'Nombre':'First name',90)}{field('lastName',es?'Apellido':'Last name',90)}</div>:field('companyName',es?'Nombre legal de la empresa agente':'Agent company legal name',200)}
      <div className="form-row">{field('street',es?'Dirección':'Street address',200)}{field('addressLine2',es?'Departamento, piso, etc. (opcional)':'Address (cont.) — optional',200,false)}</div>{field('city',es?'Ciudad':'City',100)}<div className="form-row"><div className="form-group"><label htmlFor="agent-state">{es?'Estado':'State'}</label><input id="agent-state" value={state} readOnly/></div>{field('postalCode',es?'Código ZIP':'ZIP code',10)}</div>
    </section>}
  </div>;
}
